name: Run PyTest on Asssignment 1
on:
  push:
    paths:
      - 'assignment1/**'
      - '.github/workflows/**'  # Include workflow changes
    pull_request:
      paths:
        - 'assignment1/**'
        - '.github/workflows/**'  # Include workflow changes

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./assignment1
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        pytest --cov=assignment1 tests/

    - name: Run profiling
      run: |
        python ./tests/profiling.py